### ISSUE TITLE
不知道可不可以做一个看板功能呢？ (Editing notes in board view)

### ISSUE THREAD

**Issue by rebron1900** [mabeyj/trilium-collection-views#16]
像是obsidian里的那样，我在trilium那里提了一个issue，[https://github.com/zadam/trilium/issues/2479](https://github.com/zadam/trilium/issues/2479)

**Comment by mabeyj** [comment]
It's possible to create a Kanban board like this with trilium-collection-views, but editing it would currently be a bit cumbersome.

trilium-collection-views uses notes as a data source. Each card in the board displays a note's title and attributes. For a to-do list, each to-do item would have to be its own note somewhere in your tree. This is different from obsidian-kanban which looks like it stores all of its board data within a single note.

Boards are currently read-only. To move notes to a different column, you have to edit the note itself. I would like to eventually implement the ability to drag and drop notes and create notes from the board view.

This is how I would set up a board like this:

* Create a board view that searches for `#todo` notes with columns for each status: `#view=board #query="#todo" #groupBy=status`

* To create a new to-do item, you would have to create a new note with attributes `#todo` and `#status` (such as `#status=incomplete`). You could create a template and use `~child:template` to prepopulate these attributes when you create new to-do notes.

* To edit a to-do item, you would have to click on its note to go to it, then edit its attributes (such as setting `#status=done` to move it to the "done" column). Adding promoted attributes to the template would make it easier to edit.
