### ISSUE TITLE
我在插入图片时报了一个错误 | I made an error in inserting the image

### ISSUE THREAD

**Issue by rebron1900** [mabeyj/trilium-collection-views#17]
我使用了trilium-collection-views创建了一个视图，并获取子类下的文章
_I use the trilium - collection - views created a view, and obtain a subclass of the article_

![image](https://user-images.githubusercontent.com/7929884/147946146-ad0786f4-f523-4bb4-bd05-ed3858968d63.png)

![image](https://user-images.githubusercontent.com/7929884/147946161-4405cbaf-03f7-4b73-ac18-2cec7ffed1c4.png)

另外，在gallery模式下，badge能不能块状显示？
_Also, in Gallery mode, can badge display blocks?_

![image](https://user-images.githubusercontent.com/7929884/147946327-f0a7340b-3ae9-4e5b-877c-af3bda1518e9.png)

**Comment by mabeyj** [comment]
> 我使用了trilium-collection-views创建了一个视图，并获取子类下的文章
> I use the trilium - collection - views created a view, and obtain a subclass of the article

Can you provide steps to reproduce this error? From the screenshots, I don't see how the error relates to triliium-collection-views. It looks like an error from Trilium itself.

> 另外，在gallery模式下，badge能不能块状显示？
> Also, in Gallery mode, can badge display blocks?

I'm not sure what you mean. Can you provide a mockup image of what this would look like?

**Comment by QingShui23** [comment]
@mabeyj  like this

![image](https://user-images.githubusercontent.com/7929884/147997497-863049a8-6fb2-408a-8f8f-3cdd5f21dcee.png)

**Comment by QingShui23** [comment]
I really wish I had a better to do list~
