### ISSUE TITLE
$title, But For Note ID

### ISSUE THREAD

**Issue by Alyx-Wander** [mabeyj/trilium-collection-views#20]
As it says on the tin. It's possible to query using $title using the collections views, and it's very helpful to use in a template because I don't need to manually point a note to itself. However, if I have two notes with the same name, both notes appear in the collection view, even if they are compelely unrelated.

Trilium generates its own unique note IDs and can search through them (note.noteId=xxxxx), and so I was wondering if it'd be possible to set up something like a $ID, which always returns the ID of the note that it's pasted on. I've already tried using the noteId search in a query and it was perfect.

**Comment by Shirobachi** [comment]
Any update so far?

**Comment by mabeyj** [comment]
This will be included in the next release which I will be working on over the next couple weeks or so.

**Comment by Shirobachi** [comment]
Ok, thanks for update very much! <3

**Comment by Shirobachi** [comment]
BTW. Do you consider add also all custom labels somehow?
