### ISSUE TITLE
how to sort notes by created time

### ISSUE THREAD

**Issue by ChenghuiS** [mabeyj/trilium-collection-views#24]
I wrote a table view to list all notes which Web Clipper creates. It works well. Then I want to sort these notes by their created time and use the below command:
`~renderNote=[Collection Views] #view=table #query="#clipType=page note.isArchived=false" #sort=note.dateCreated`
But it does not work, is anything wrong?

**Comment by mabeyj** [comment]
This is not possible at this time. Note metadata like the creation time are not the same as note attributes, and sort currently only works with attributes. I will look into adding support for this.
