### ISSUE TITLE
can't see values of $dateModified or $dateCreated in the results

### ISSUE THREAD

**Issue by markbj71** [mabeyj/trilium-collection-views#41]
![image](https://github.com/mabeyj/trilium-collection-views/assets/58618994/fd4f13c8-3793-48ac-b848-6561c95b896a)

**Comment by mabeyj** [comment]
Are you using Trilium 0.61?

These dates work for me in 0.60, but not in 0.61. It appears they have been renamed in Trilium's API in 0.61 which is the cause of the breakage. Also, it looks like date created is not returned by the API anymore, so I may have to submit a bug report to have it added back in before this can be fully fixed.

**Comment by markbj71** [comment]
thanks!

**Comment by mabeyj** [comment]
v1.2.1 is now released which fixes this, and you'll have to upgrade Trilium to v0.61.6 as well. Thanks for reporting!
